# Generated by Django 5.2.4 on 2025-07-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
